### ISSUE TITLE
ServoToPoseAction is not available

### ISSUE THREAD

**Issue by Dyymon** [qcr/armer#15]
https://github.com/qcr/armer/blob/ceeb2dc2b8a20ff88a217d9a4c125a4c195f9a8b/examples/panda_example.py#L12

Hi,
the panda example fails because armer_msgs doesn't have all messages and actions defined.
Best,
Jan

**Comment by DasGuna** [comment]
Hi Dyymon, 

Sorry this is so late. The ServoToPose is now a topic to publish to (with a new ServoStamped message type available in armer_msgs). 

If there are still any issues, happy to look into it!

Closing this for now
